import{z}from"zod";export const inventorySchema=z.object({name:z.string().trim().min(1).max(120),category:z.string().trim().max(80).nullable().optional(),brand:z.string().trim().max(80).nullable().optional(),barcode:z.string().trim().max(32).nullable().optional(),quantity:z.coerce.number().positive().max(100000),unit:z.string().trim().min(1).max(30),purchase_date:z.string().nullable().optional(),expiration_date:z.string().nullable().optional(),expiration_source:z.enum(["package_scan","manual","manufacturer_data","estimated","unknown"]),opened_date:z.string().nullable().optional(),storage_location:z.enum(["refrigerator","freezer","pantry","other"]),unit_price:z.coerce.number().nonnegative().nullable().optional(),notes:z.string().trim().max(1000).nullable().optional()});export const usageSchema=z.object({inventory_item_id:z.string().uuid(),action:z.enum(["consumed","cooked","finished","discarded","donated","correction"]),quantity:z.coerce.number().positive(),unit:z.string().min(1).max(30),note:z.string().max(500).optional(),used_at:z.string().datetime().optional()});export const receiptAiSchema=z.object({storeName:z.string().nullable(),purchaseDate:z.string().nullable(),currency:z.string().length(3),subtotal:z.number().nullable(),tax:z.number().nullable(),total:z.number().nullable(),items:z.array(z.object({rawName:z.string().min(1),normalizedName:z.string().min(1),quantity:z.number().positive(),unit:z.string(),unitPrice:z.number().nullable(),totalPrice:z.number().nullable(),category:z.string().nullable(),addToInventory:z.boolean().default(true)})).min(1),mock:z.boolean().optional()});

export const foodRecognitionSchema=z.object({items:z.array(z.object({name:z.string().min(1).max(120),category:z.string().max(80).nullable(),estimatedQuantity:z.number().positive(),unit:z.string().min(1).max(30),confidence:z.number().min(0).max(1)})).min(1),mock:z.boolean().optional()});
export const expirationRecognitionSchema=z.object({dates:z.array(z.object({value:z.string().nullable(),label:z.string().nullable(),confidence:z.number().min(0).max(1),yearMissing:z.boolean(),suggestedYear:z.number().int().min(2000).max(2200).nullable(),nearbyText:z.string().nullable()})),mock:z.boolean().optional()});
export const recipeIngredientSchema=z.object({name:z.string().min(1),quantity:z.number().positive(),unit:z.string().min(1),inventoryItemId:z.string().uuid().nullable().optional(),available:z.boolean().optional()});
export const recipeSchema=z.object({title:z.string().min(1).max(160),description:z.string().max(600),difficulty:z.enum(["Easy","Medium","Hard"]),cookingTimeMinutes:z.number().int().positive().max(360),servings:z.number().int().positive().max(20),ingredientsUsed:z.array(recipeIngredientSchema),missingIngredients:z.array(recipeIngredientSchema),steps:z.array(z.string().min(1)).min(1),safetyNotes:z.array(z.string()),mock:z.boolean().optional()});
export const recipesResponseSchema=z.object({recipes:z.array(recipeSchema).min(1).max(5),mock:z.boolean().optional()});
export const recipeRequestSchema=z.object({maxCookingTime:z.number().int().min(5).max(360).default(30),difficulty:z.enum(["Any","Easy","Medium","Hard"]).default("Any"),servings:z.number().int().min(1).max(20).default(2),dietaryPreferences:z.string().max(500).default(""),allergies:z.string().max(500).default(""),excludeIngredients:z.string().max(500).default("")});
export const webRecipeSchema=z.object({title:z.string().min(1),sourceDomain:z.string().min(1),sourceUrl:z.string().url(),summary:z.string().min(1).max(600),ingredientsHighlighted:z.array(z.string()),mock:z.boolean().optional()});
export const webRecipeResponseSchema=z.object({results:z.array(webRecipeSchema).max(8),mock:z.boolean().optional()});
export const recipeSearchRequestSchema=z.object({query:z.string().trim().min(2).max(200),includeInventory:z.boolean().default(true)});
export const notificationRegistrationSchema=z.object({token:z.string().min(20).max(4096),deviceName:z.string().max(100).optional()});
