"use client";
import { useState } from "react";
import { AlertTriangle, LoaderCircle } from "lucide-react";
import { CameraCapture } from "./camera-capture";
import { uploadFoodImage } from "@/lib/client-upload";
import { expirationRecognitionSchema } from "@/lib/validation";
import type { ExpirationCandidate, InventoryItem } from "@/lib/types";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";
import { useI18n } from "./locale-provider";

export function ExpirationScanner({inventory}:{inventory:InventoryItem[]}){const {locale}=useI18n();const ja=locale==="ja";const router=useRouter();const [file,setFile]=useState<File>();const [dates,setDates]=useState<ExpirationCandidate[]>();const [selected,setSelected]=useState(0);const [itemId,setItemId]=useState(inventory[0]?.id??"");const [confirmedDate,setConfirmedDate]=useState("");const [mock,setMock]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function read(){if(!file)return;setBusy(true);setError("");try{const {path}=await uploadFoodImage(file);const response=await fetch("/api/ai/read-expiration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({imagePath:path})});const body=await response.json();if(!response.ok)throw new Error(body.error);const parsed=expirationRecognitionSchema.parse(body);setDates(parsed.dates);setMock(Boolean(parsed.mock));setConfirmedDate(parsed.dates[0]?.value??"");}catch(e){setError(e instanceof Error?e.message:"Date recognition failed");}finally{setBusy(false);}}
 async function save(){if(!itemId||!confirmedDate)return;setBusy(true);const supabase=createClient();const {error:saveError}=await supabase.from("inventory_items").update({expiration_date:confirmedDate,expiration_source:"package_scan",updated_at:new Date().toISOString()}).eq("id",itemId);setBusy(false);if(saveError){setError("Could not save the date");return;}router.push(`/inventory/${itemId}`);router.refresh();}
 if(!dates)return <div><CameraCapture onCapture={setFile}/><button className="btn-primary mt-4 w-full" disabled={!file||busy} onClick={read}>{busy&&<LoaderCircle className="animate-spin"/>}{ja?"期限を読み取る":"Read expiration label"}</button>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<p className="mt-4 text-xs text-[#687970]">{ja?"年がない場合は自動確定しません。期限だけで安全性は判断できません。":"A missing year is never silently confirmed. A date alone cannot determine food safety."}</p></div>;
 return <div className="space-y-4">{mock&&<p className="rounded-xl bg-amber-50 p-3 text-sm">{ja?"モックAI結果です。":"Mock AI result."}</p>} {!dates.length&&<p className="card p-5">{ja?"日付が見つかりませんでした。手動で入力してください。":"No date found. Enter it manually below."}</p>}<label><span className="label">{ja?"在庫の食品":"Inventory item"}</span><select className="input" value={itemId} onChange={(e)=>setItemId(e.target.value)}>{inventory.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{dates.length>0&&<fieldset className="space-y-2"><legend className="label">{ja?"候補":"Candidates"}</legend>{dates.map((date,index)=><label key={index} className="card flex gap-3 p-3"><input type="radio" checked={selected===index} onChange={()=>{setSelected(index);setConfirmedDate(date.value??"")}}/><span><b>{date.value??`${date.suggestedYear??"?"}-MM-DD`}</b> · {date.label??"Unknown label"} · {Math.round(date.confidence*100)}%{date.yearMissing&&<span className="mt-1 flex gap-1 text-xs text-amber-800"><AlertTriangle size={14}/>{ja?"年を確認してください":"Confirm the year"}</span>}</span></label>)}</fieldset>}<label><span className="label">{ja?"確認した期限":"Confirmed date"}</span><input className="input" type="date" value={confirmedDate} onChange={(e)=>setConfirmedDate(e.target.value)} required/></label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button className="btn-primary w-full" disabled={!itemId||!confirmedDate||busy} onClick={save}>{ja?"期限を保存":"Save confirmed date"}</button></div>}
