"use client";
import { useState } from "react";
import { AlertTriangle, LoaderCircle, Plus, Trash2 } from "lucide-react";
import { CameraCapture } from "./camera-capture";
import { uploadFoodImage } from "@/lib/client-upload";
import { foodRecognitionSchema } from "@/lib/validation";
import type { DetectedFood } from "@/lib/types";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { useI18n } from "./locale-provider";

export function FoodScanner(){const {locale}=useI18n();const ja=locale==="ja";const router=useRouter();const [file,setFile]=useState<File>();const [items,setItems]=useState<DetectedFood[]>();const [imagePath,setImagePath]=useState("");const [mock,setMock]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function recognize(){if(!file)return;setBusy(true);setError("");try{const uploaded=await uploadFoodImage(file);setImagePath(uploaded.path);const response=await fetch("/api/ai/recognize-food",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({imagePath:uploaded.path})});const body=await response.json();if(!response.ok)throw new Error(body.error);const parsed=foodRecognitionSchema.parse(body);setItems(parsed.items);setMock(Boolean(parsed.mock));}catch(e){setError(e instanceof Error?e.message:"Recognition failed");}finally{setBusy(false);}}
 function update(index:number,key:keyof DetectedFood,value:string|number|null){setItems((current)=>current?.map((item,i)=>i===index?{...item,[key]:value}:item));}
 async function save(){if(!items?.length)return;setBusy(true);setError("");try{const {user,supabase}=await uploadFoodImageGuard();const {error:saveError}=await supabase.from("inventory_items").insert(items.map((item)=>({user_id:user.id,name:item.name,category:item.category,quantity:item.estimatedQuantity,unit:item.unit,image_path:imagePath,expiration_source:"unknown",storage_location:"other",status:"available"})));if(saveError)throw new Error("Could not save inventory items");toast.success(ja?"在庫に追加しました":"Added to inventory");router.push("/inventory");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy(false);}}
 if(!items)return <div><CameraCapture onCapture={setFile}/><button className="btn-primary mt-4 w-full" disabled={!file||busy} onClick={recognize}>{busy&&<LoaderCircle className="animate-spin"/>}{ja?"食品を認識":"Recognize food"}</button>{error&&<p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<p className="mt-4 text-xs text-[#687970]">{ja?"AIの結果は提案です。保存前にすべて確認してください。":"AI results are suggestions. Confirm every item before saving."}</p></div>;
 return <div className="space-y-4">{mock&&<Notice text={ja?"モックAI結果です。":"Mock AI result — no paid request was made."}/>} {items.map((item,index)=><article className="card p-4" key={index}><div className="mb-3 flex justify-between"><b>{ja?`食品 ${index+1}`:`Food ${index+1}`}</b><button aria-label="Remove" onClick={()=>setItems(items.filter((_,i)=>i!==index))}><Trash2 size={18}/></button></div>{item.confidence<.7&&<Notice text={ja?"信頼度が低いため、内容をよく確認してください。":"Low confidence — review this item carefully."}/>}<div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label={ja?"名前":"Name"} value={item.name} onChange={(v)=>update(index,"name",v)}/><Field label={ja?"カテゴリ":"Category"} value={item.category??""} onChange={(v)=>update(index,"category",v||null)}/><Field label={ja?"数量":"Quantity"} type="number" value={item.estimatedQuantity} onChange={(v)=>update(index,"estimatedQuantity",Number(v))}/><Field label={ja?"単位":"Unit"} value={item.unit} onChange={(v)=>update(index,"unit",v)}/></div><p className="mt-3 text-xs text-[#687970]">Confidence {Math.round(item.confidence*100)}%</p></article>)}<button className="btn-secondary" onClick={()=>setItems([...items,{name:"",category:null,estimatedQuantity:1,unit:ja?"個":"piece",confidence:1}])}><Plus size={18}/>{ja?"食品を追加":"Add item"}</button>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button className="btn-primary w-full" disabled={busy||!items.length} onClick={save}>{busy&&<LoaderCircle className="animate-spin"/>}{ja?"確認して在庫に保存":"Confirm and save to inventory"}</button></div>;
}
async function uploadFoodImageGuard(){const {createClient}=await import("@/lib/supabase/client");const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Session expired");return {user,supabase};}
function Field({label,value,onChange,type="text"}:{label:string;value:string|number;onChange:(v:string)=>void;type?:string}){return <label><span className="label">{label}</span><input className="input" type={type} min={type==="number"?"0.001":undefined} step={type==="number"?"any":undefined} value={value} onChange={(e)=>onChange(e.target.value)} required/></label>}
function Notice({text}:{text:string}){return <p className="flex gap-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><AlertTriangle size={18}/>{text}</p>}
