"use client";
import { useState } from "react";
import { Bell, BellOff, Check, LoaderCircle } from "lucide-react";
import { env } from "@/lib/env";
import { useI18n } from "./locale-provider";

type NotificationRow={id:string;title:string;message:string;created_at:string;read_at:string|null};
export function NotificationSettings({initialDays,initialTime,notifications}:{initialDays:number[];initialTime:number;notifications:NotificationRow[]}){const {locale}=useI18n();const ja=locale==="ja";const [days,setDays]=useState(initialDays);const [time,setTime]=useState(initialTime);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [rows,setRows]=useState(notifications);
 const firebaseConfigured=Boolean(env.NEXT_PUBLIC_FIREBASE_API_KEY&&env.NEXT_PUBLIC_FIREBASE_PROJECT_ID&&env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID&&env.NEXT_PUBLIC_FIREBASE_APP_ID&&env.NEXT_PUBLIC_FIREBASE_VAPID_KEY);
 async function enablePush(){setBusy(true);setMessage("");try{if(!firebaseConfigured)throw new Error(ja?"Firebaseの公開設定が未設定です。":"Firebase public configuration is missing.");if(!("Notification" in window)||!("serviceWorker" in navigator))throw new Error(ja?"このブラウザはプッシュ通知に対応していません。":"Push notifications are not supported in this browser.");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error(ja?"通知が許可されませんでした。":"Notification permission was not granted.");const [{initializeApp,getApps},{getMessaging,getToken,isSupported}]=await Promise.all([import("firebase/app"),import("firebase/messaging")]);if(!(await isSupported()))throw new Error(ja?"このブラウザではFirebase通知を利用できません。":"Firebase messaging is unsupported in this browser.");const app=getApps()[0]??initializeApp({apiKey:env.NEXT_PUBLIC_FIREBASE_API_KEY,authDomain:env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,projectId:env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,storageBucket:env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,messagingSenderId:env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,appId:env.NEXT_PUBLIC_FIREBASE_APP_ID});const registration=await navigator.serviceWorker.ready;const token=await getToken(getMessaging(app),{vapidKey:env.NEXT_PUBLIC_FIREBASE_VAPID_KEY,serviceWorkerRegistration:registration});if(!token)throw new Error("No notification token returned");const response=await fetch("/api/notifications/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,deviceName:navigator.userAgent.slice(0,100)})});if(!response.ok)throw new Error((await response.json()).error);localStorage.setItem("mhungry-fcm-token",token);setMessage(ja?"この端末の通知を有効にしました。":"Push notifications enabled for this device.");}catch(e){setMessage(e instanceof Error?e.message:"Push setup failed");}finally{setBusy(false);}}
 async function disablePush(){setBusy(true);const token=localStorage.getItem("mhungry-fcm-token");if(token)await fetch("/api/notifications/register",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})});localStorage.removeItem("mhungry-fcm-token");setMessage(ja?"この端末の通知を無効にしました。":"Push notifications disabled for this device.");setBusy(false);}
 async function save(){setBusy(true);const response=await fetch("/api/notifications/preferences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reminderDays:days,preferredCookingTime:time})});setMessage(response.ok?(ja?"設定を保存しました。":"Preferences saved."):(await response.json()).error);setBusy(false);}
 async function markAll(){await fetch("/api/notifications/read",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true})});setRows(rows.map((row)=>({...row,read_at:new Date().toISOString()})));}
 return <div className="space-y-6"><section className="card p-6"><h2 className="flex items-center gap-2 text-2xl"><Bell size={22}/>{ja?"期限リマインダー":"Expiration reminders"}</h2><fieldset className="mt-4"><legend className="label">{ja?"通知するタイミング":"Notify me"}</legend><div className="flex flex-wrap gap-3">{[0,1,3,7].map((day)=><label className="flex items-center gap-2" key={day}><input type="checkbox" checked={days.includes(day)} onChange={(e)=>setDays(e.target.checked?[...days,day]:days.filter((value)=>value!==day))}/>{day===0?(ja?"当日":"On expiry date"):(ja?`${day}日前`:`${day} day${day>1?"s":""} before`)}</label>)}</div></fieldset><label className="mt-4 block"><span className="label">{ja?"希望調理時間（分）":"Preferred cooking time (minutes)"}</span><input className="input max-w-40" type="number" min="5" max="360" value={time} onChange={(e)=>setTime(Number(e.target.value))}/></label><button className="btn-primary mt-4" disabled={busy||!days.length} onClick={save}>{busy&&<LoaderCircle className="animate-spin"/>}{ja?"設定を保存":"Save preferences"}</button></section><section className="card p-6"><h2 className="text-2xl">{ja?"プッシュ通知":"Push notifications"}</h2><p className="mt-2 text-sm text-[#64756d]">{ja?"利用できない場合でも、アプリ内通知は作成されます。":"In-app notifications still work when Firebase is unavailable."}</p><div className="mt-4 flex flex-wrap gap-2"><button className="btn-primary" disabled={busy} onClick={enablePush}><Bell size={18}/>{ja?"この端末で有効化":"Enable on this device"}</button><button className="btn-secondary" disabled={busy} onClick={disablePush}><BellOff size={18}/>{ja?"この端末から削除":"Remove this device"}</button></div>{message&&<p role="status" className="mt-3 rounded-xl bg-[#edf3ea] p-3 text-sm">{message}</p>}</section><section className="card p-6"><div className="flex items-center justify-between"><h2 className="text-2xl">{ja?"アプリ内通知":"Notifications"}</h2>{rows.some((row)=>!row.read_at)&&<button className="text-sm font-bold underline" onClick={markAll}>{ja?"すべて既読":"Mark all read"}</button>}</div>{rows.length?<div className="mt-4 space-y-3">{rows.map((row)=><article className={`rounded-xl border p-3 ${row.read_at?"bg-white":"border-amber-300 bg-amber-50"}`} key={row.id}><div className="flex gap-2"><Check size={16}/><div><b>{row.title}</b><p className="mt-1 text-sm">{row.message}</p><time className="mt-1 block text-xs text-[#64756d]">{new Date(row.created_at).toLocaleString(locale==="ja"?"ja-JP":"en-US")}</time></div></div></article>)}</div>:<p className="mt-4 text-sm text-[#64756d]">{ja?"通知はまだありません。":"No notifications yet."}</p>}</section></div>}
