create extension if not exists pgcrypto;
create type public.inventory_status as enum ('available','finished','discarded','donated','expired');
create type public.expiration_source as enum ('package_scan','manual','manufacturer_data','estimated','unknown');
create type public.storage_location as enum ('refrigerator','freezer','pantry','other');
create type public.usage_action as enum ('consumed','cooked','finished','discarded','donated','correction');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,language text not null default 'en',timezone text not null default 'UTC',dietary_preferences text[] not null default '{}',allergies text[] not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.receipts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,image_path text,store_name text,purchase_date date,currency text not null default 'JPY',subtotal numeric(12,2),tax numeric(12,2),total_amount numeric(12,2),raw_ocr_text text,processing_status text not null default 'confirmed',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.purchases(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,receipt_id uuid references public.receipts(id) on delete set null,store_name text,purchase_date date,currency text not null default 'JPY',total_amount numeric(12,2),created_at timestamptz not null default now());
create table public.purchase_items(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,purchase_id uuid not null references public.purchases(id) on delete cascade,raw_name text not null,normalized_name text not null,category text,brand text,barcode text,quantity numeric(12,3) not null check(quantity>0),unit text not null,unit_price numeric(12,2),total_price numeric(12,2),added_to_inventory boolean not null default false,created_at timestamptz not null default now());
create table public.inventory_items(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,purchase_item_id uuid references public.purchase_items(id) on delete set null,name text not null,category text,brand text,barcode text,quantity numeric(12,3) not null check(quantity>=0),unit text not null,purchase_date date,expiration_date date,expiration_source public.expiration_source not null default 'unknown',opened_date date,storage_location public.storage_location not null default 'other',unit_price numeric(12,2),estimated_value numeric(12,2),image_path text,notes text,status public.inventory_status not null default 'available',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.usage_logs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,inventory_item_id uuid references public.inventory_items(id) on delete set null,action public.usage_action not null,quantity numeric(12,3) not null check(quantity>0),unit text not null,estimated_value numeric(12,2),note text,used_at timestamptz not null default now(),created_at timestamptz not null default now());
create table public.recipes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,description text,source_type text not null,source_url text,source_domain text,cooking_time_minutes integer,difficulty text,servings integer,ingredients_json jsonb not null default '[]',steps_json jsonb not null default '[]',safety_notes_json jsonb not null default '[]',created_at timestamptz not null default now());
create table public.notification_subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,provider text not null,token text not null unique,device_name text,enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,inventory_item_id uuid references public.inventory_items(id) on delete cascade,notification_type text not null,title text not null,message text not null,scheduled_for timestamptz,sent_at timestamptz,read_at timestamptz,delivery_status text not null default 'pending',reminder_days integer,created_at timestamptz not null default now(),unique(inventory_item_id,reminder_days,scheduled_for));
create table public.user_settings(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,reminder_days integer[] not null default '{0,1,3}',push_enabled boolean not null default false,email_enabled boolean not null default false,default_storage_location public.storage_location not null default 'refrigerator',preferred_cooking_time integer default 30,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create index inventory_user_idx on public.inventory_items(user_id);create index inventory_expiry_idx on public.inventory_items(expiration_date);create index inventory_status_idx on public.inventory_items(status);create index inventory_barcode_idx on public.inventory_items(barcode);create index receipts_user_idx on public.receipts(user_id);create index receipts_purchase_date_idx on public.receipts(purchase_date);create index purchases_user_idx on public.purchases(user_id);create index purchases_date_idx on public.purchases(purchase_date);create index purchase_items_user_idx on public.purchase_items(user_id);create index usage_user_idx on public.usage_logs(user_id);create index usage_used_at_idx on public.usage_logs(used_at);create index notifications_user_idx on public.notifications(user_id);create index notifications_delivery_idx on public.notifications(delivery_status);

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,display_name) values(new.id,new.raw_user_meta_data->>'display_name');insert into public.user_settings(user_id) values(new.id);return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create function public.record_inventory_usage(p_inventory_item_id uuid,p_action public.usage_action,p_quantity numeric,p_unit text,p_note text,p_estimated_value numeric,p_remaining numeric,p_status public.inventory_status) returns void language plpgsql security invoker set search_path=public as $$begin if not exists(select 1 from public.inventory_items where id=p_inventory_item_id and user_id=auth.uid()) then raise exception 'not authorized';end if;insert into public.usage_logs(user_id,inventory_item_id,action,quantity,unit,note,estimated_value) values(auth.uid(),p_inventory_item_id,p_action,p_quantity,p_unit,p_note,p_estimated_value);update public.inventory_items set quantity=p_remaining,status=p_status,updated_at=now() where id=p_inventory_item_id and user_id=auth.uid();end$$;

create function public.confirm_receipt(p_image_path text,p_store_name text,p_purchase_date date,p_currency text,p_subtotal numeric,p_tax numeric,p_total numeric,p_items jsonb) returns uuid language plpgsql security invoker set search_path=public as $$declare v_receipt uuid;v_purchase uuid;v_item jsonb;v_purchase_item uuid;begin if p_image_path not like auth.uid()::text||'/%' then raise exception 'invalid path';end if;insert into public.receipts(user_id,image_path,store_name,purchase_date,currency,subtotal,tax,total_amount) values(auth.uid(),p_image_path,p_store_name,p_purchase_date,p_currency,p_subtotal,p_tax,p_total) returning id into v_receipt;insert into public.purchases(user_id,receipt_id,store_name,purchase_date,currency,total_amount) values(auth.uid(),v_receipt,p_store_name,p_purchase_date,p_currency,p_total) returning id into v_purchase;for v_item in select * from jsonb_array_elements(p_items) loop insert into public.purchase_items(user_id,purchase_id,raw_name,normalized_name,category,quantity,unit,unit_price,total_price,added_to_inventory) values(auth.uid(),v_purchase,v_item->>'rawName',v_item->>'normalizedName',v_item->>'category',(v_item->>'quantity')::numeric,v_item->>'unit',nullif(v_item->>'unitPrice','')::numeric,nullif(v_item->>'totalPrice','')::numeric,coalesce((v_item->>'addToInventory')::boolean,false)) returning id into v_purchase_item;if coalesce((v_item->>'addToInventory')::boolean,false) then insert into public.inventory_items(user_id,purchase_item_id,name,category,quantity,unit,purchase_date,expiration_source,storage_location,unit_price,estimated_value) values(auth.uid(),v_purchase_item,v_item->>'normalizedName',v_item->>'category',(v_item->>'quantity')::numeric,v_item->>'unit',p_purchase_date,'unknown','refrigerator',nullif(v_item->>'unitPrice','')::numeric,nullif(v_item->>'totalPrice','')::numeric);end if;end loop;return v_purchase;end$$;

do $$declare t text;begin foreach t in array array['profiles','receipts','purchases','purchase_items','inventory_items','usage_logs','recipes','notification_subscriptions','notifications','user_settings'] loop execute format('alter table public.%I enable row level security',t);execute format('create policy %I on public.%I for select to authenticated using (%s)',t||'_select',t,case when t='profiles' then 'id=auth.uid()' else 'user_id=auth.uid()' end);execute format('create policy %I on public.%I for insert to authenticated with check (%s)',t||'_insert',t,case when t='profiles' then 'id=auth.uid()' else 'user_id=auth.uid()' end);execute format('create policy %I on public.%I for update to authenticated using (%s) with check (%s)',t||'_update',t,case when t='profiles' then 'id=auth.uid()' else 'user_id=auth.uid()' end,case when t='profiles' then 'id=auth.uid()' else 'user_id=auth.uid()' end);execute format('create policy %I on public.%I for delete to authenticated using (%s)',t||'_delete',t,case when t='profiles' then 'id=auth.uid()' else 'user_id=auth.uid()' end);end loop;end$$;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('receipts','receipts',false,15728640,array['image/jpeg','image/png','image/webp','image/heic','image/heif']),('food-images','food-images',false,15728640,array['image/jpeg','image/png','image/webp','image/heic','image/heif']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "user image select" on storage.objects for select to authenticated using(bucket_id in('receipts','food-images') and (storage.foldername(name))[1]=auth.uid()::text);
create policy "user image insert" on storage.objects for insert to authenticated with check(bucket_id in('receipts','food-images') and (storage.foldername(name))[1]=auth.uid()::text);
create policy "user image update" on storage.objects for update to authenticated using(bucket_id in('receipts','food-images') and (storage.foldername(name))[1]=auth.uid()::text);
create policy "user image delete" on storage.objects for delete to authenticated using(bucket_id in('receipts','food-images') and (storage.foldername(name))[1]=auth.uid()::text);
